name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Run tests with Maven
        env:
            dev_sensor_api_key: ${{ secrets.DEV_SENSOR_API_KEY }}
            dev_sensor_static_password: ${{ secrets.DEV_SENSOR_STATIC_PASSWORD }}
            dev_sensor_static_username: ${{ secrets.DEV_SENSOR_STATIC_USERNAME }}
            dev_skycell_api_key: ${{ secrets.DEV_SKYCELL_API_KEY }}
            dev_skycell_static_password: ${{ secrets.DEV_SKYCELL_STATIC_PASSWORD }}
            dev_skycell_static_username: ${{ secrets.DEV_SKYCELL_STATIC_USERNAME }}
            logger_nex_mr810t: ${{ secrets.LOGGER_NEX_MR810T }}
            logger_nex_mr812p: ${{ secrets.LOGGER_NEX_MR812P }}
        run: mvn test
